// Colonias de CDMX con alcaldía y código postal
export const COLONIAS = [
  { colonia: 'Centro', alcaldia: 'Cuauhtémoc', cp: '06000' },
  { colonia: 'Juárez', alcaldia: 'Cuauhtémoc', cp: '06600' },
  { colonia: 'Roma Norte', alcaldia: 'Cuauhtémoc', cp: '06700' },
  { colonia: 'Roma Sur', alcaldia: 'Cuauhtémoc', cp: '06760' },
  { colonia: 'Condesa', alcaldia: 'Cuauhtémoc', cp: '06140' },
  { colonia: 'Hipódromo', alcaldia: 'Cuauhtémoc', cp: '06100' },
  { colonia: 'Hipódromo Condesa', alcaldia: 'Cuauhtémoc', cp: '06170' },
  { colonia: 'Doctores', alcaldia: 'Cuauhtémoc', cp: '06720' },
  { colonia: 'Obrera', alcaldia: 'Cuauhtémoc', cp: '06800' },
  { colonia: 'San Rafael', alcaldia: 'Cuauhtémoc', cp: '06470' },
  { colonia: 'Santa María la Ribera', alcaldia: 'Cuauhtémoc', cp: '06400' },
  { colonia: 'Guerrero', alcaldia: 'Cuauhtémoc', cp: '06300' },
  { colonia: 'Buenavista', alcaldia: 'Cuauhtémoc', cp: '06350' },
  { colonia: 'Tabacalera', alcaldia: 'Cuauhtémoc', cp: '06030' },
  { colonia: 'Cuauhtémoc', alcaldia: 'Cuauhtémoc', cp: '06500' },
  { colonia: 'Tlatelolco', alcaldia: 'Cuauhtémoc', cp: '06900' },
  { colonia: 'Polanco', alcaldia: 'Miguel Hidalgo', cp: '11550' },
  { colonia: 'Polanco V Sección', alcaldia: 'Miguel Hidalgo', cp: '11560' },
  { colonia: 'Anzures', alcaldia: 'Miguel Hidalgo', cp: '11590' },
  { colonia: 'Lomas de Chapultepec', alcaldia: 'Miguel Hidalgo', cp: '11000' },
  { colonia: 'Lomas Altas', alcaldia: 'Miguel Hidalgo', cp: '11950' },
  { colonia: 'Lomas de Sotelo', alcaldia: 'Miguel Hidalgo', cp: '11200' },
  { colonia: 'Bosques de las Lomas', alcaldia: 'Miguel Hidalgo', cp: '11700' },
  { colonia: 'Tacubaya', alcaldia: 'Miguel Hidalgo', cp: '11870' },
  { colonia: 'Escandón I Sección', alcaldia: 'Miguel Hidalgo', cp: '11800' },
  { colonia: 'Escandón II Sección', alcaldia: 'Miguel Hidalgo', cp: '11820' },
  { colonia: 'San Miguel Chapultepec', alcaldia: 'Miguel Hidalgo', cp: '11850' },
  { colonia: 'Anáhuac', alcaldia: 'Miguel Hidalgo', cp: '11320' },
  { colonia: 'Pensil', alcaldia: 'Miguel Hidalgo', cp: '11410' },
  { colonia: 'Popotla', alcaldia: 'Miguel Hidalgo', cp: '11400' },
  { colonia: 'San Joaquín', alcaldia: 'Miguel Hidalgo', cp: '11340' },
  { colonia: 'Tlatilco', alcaldia: 'Miguel Hidalgo', cp: '11290' },
  { colonia: 'Nápoles', alcaldia: 'Benito Juárez', cp: '03810' },
  { colonia: 'Narvarte', alcaldia: 'Benito Juárez', cp: '03020' },
  { colonia: 'Del Valle Norte', alcaldia: 'Benito Juárez', cp: '03100' },
  { colonia: 'Del Valle Centro', alcaldia: 'Benito Juárez', cp: '03100' },
  { colonia: 'Del Valle Sur', alcaldia: 'Benito Juárez', cp: '03230' },
  { colonia: 'Portales Norte', alcaldia: 'Benito Juárez', cp: '03300' },
  { colonia: 'Portales Sur', alcaldia: 'Benito Juárez', cp: '03300' },
  { colonia: 'Álamos', alcaldia: 'Benito Juárez', cp: '03400' },
  { colonia: 'Xoco', alcaldia: 'Benito Juárez', cp: '03330' },
  { colonia: 'Santa Cruz Atoyac', alcaldia: 'Benito Juárez', cp: '03310' },
  { colonia: 'Mixcoac', alcaldia: 'Benito Juárez', cp: '03910' },
  { colonia: 'San Pedro de los Pinos', alcaldia: 'Benito Juárez', cp: '03800' },
  { colonia: 'Colonia del Valle', alcaldia: 'Benito Juárez', cp: '03100' },
  { colonia: 'Coyoacán Centro', alcaldia: 'Coyoacán', cp: '04000' },
  { colonia: 'Del Carmen', alcaldia: 'Coyoacán', cp: '04100' },
  { colonia: 'Campestre Churubusco', alcaldia: 'Coyoacán', cp: '04200' },
  { colonia: 'Churubusco Country Club', alcaldia: 'Coyoacán', cp: '04210' },
  { colonia: 'Santa Úrsula Coapa', alcaldia: 'Coyoacán', cp: '04650' },
  { colonia: 'Xotepingo', alcaldia: 'Coyoacán', cp: '04640' },
  { colonia: 'Villa Coyoacán', alcaldia: 'Coyoacán', cp: '04000' },
  { colonia: 'Santo Domingo', alcaldia: 'Coyoacán', cp: '04369' },
  { colonia: 'San Ángel', alcaldia: 'Álvaro Obregón', cp: '01000' },
  { colonia: 'Chimalistac', alcaldia: 'Álvaro Obregón', cp: '01070' },
  { colonia: 'Guadalupe Inn', alcaldia: 'Álvaro Obregón', cp: '01020' },
  { colonia: 'Florida', alcaldia: 'Álvaro Obregón', cp: '01030' },
  { colonia: 'Merced Gómez', alcaldia: 'Álvaro Obregón', cp: '01600' },
  { colonia: 'Álvaro Obregón Centro', alcaldia: 'Álvaro Obregón', cp: '01000' },
  { colonia: 'Lindavista', alcaldia: 'Gustavo A. Madero', cp: '07300' },
  { colonia: 'San Juan de Aragón', alcaldia: 'Gustavo A. Madero', cp: '07920' },
  { colonia: 'Villa Gustavo A. Madero', alcaldia: 'Gustavo A. Madero', cp: '07050' },
  { colonia: 'Cuchilla La Joya', alcaldia: 'Gustavo A. Madero', cp: '07840' },
  { colonia: 'La Villa', alcaldia: 'Gustavo A. Madero', cp: '07000' },
  { colonia: 'Vallejo', alcaldia: 'Gustavo A. Madero', cp: '07870' },
  { colonia: 'Progreso Nacional', alcaldia: 'Gustavo A. Madero', cp: '07600' },
  { colonia: 'Cuchilla del Tesoro', alcaldia: 'Gustavo A. Madero', cp: '07630' },
  { colonia: 'La Malinche', alcaldia: 'Gustavo A. Madero', cp: '07210' },
  { colonia: 'San Pedro Zacatenco', alcaldia: 'Gustavo A. Madero', cp: '07360' },
  { colonia: 'Nueva Santa María', alcaldia: 'Gustavo A. Madero', cp: '02800' },
  { colonia: 'Clavería', alcaldia: 'Azcapotzalco', cp: '02080' },
  { colonia: 'Centro de Azcapotzalco', alcaldia: 'Azcapotzalco', cp: '02000' },
  { colonia: 'Industrial Vallejo', alcaldia: 'Azcapotzalco', cp: '02300' },
  { colonia: 'San Rafael Chamapa', alcaldia: 'Azcapotzalco', cp: '02410' },
  { colonia: 'Reynosa Tamaulipas', alcaldia: 'Azcapotzalco', cp: '02250' },
  { colonia: 'El Rosario', alcaldia: 'Azcapotzalco', cp: '02100' },
  { colonia: 'San Miguel Amantla', alcaldia: 'Azcapotzalco', cp: '02700' },
  { colonia: 'Tlalpan Centro', alcaldia: 'Tlalpan', cp: '14000' },
  { colonia: 'Villa Coapa', alcaldia: 'Tlalpan', cp: '14390' },
  { colonia: 'Ex Hacienda Coapa', alcaldia: 'Tlalpan', cp: '14300' },
  { colonia: 'Prado Coapa 1a Sección', alcaldia: 'Tlalpan', cp: '14350' },
  { colonia: 'San Andrés Totoltepec', alcaldia: 'Tlalpan', cp: '14400' },
  { colonia: 'Iztacalco Centro', alcaldia: 'Iztacalco', cp: '08600' },
  { colonia: 'Ramos Millán', alcaldia: 'Iztacalco', cp: '08730' },
  { colonia: 'Agrícola Oriental', alcaldia: 'Iztacalco', cp: '08500' },
  { colonia: 'Unidad Habitacional IMSS', alcaldia: 'Iztacalco', cp: '08300' },
  { colonia: 'Iztapalapa Centro', alcaldia: 'Iztapalapa', cp: '09000' },
  { colonia: 'Santa Martha Acatitla', alcaldia: 'Iztapalapa', cp: '09510' },
  { colonia: 'San Lorenzo Tezonco', alcaldia: 'Iztapalapa', cp: '09900' },
  { colonia: 'U.H. Vicente Guerrero', alcaldia: 'Iztapalapa', cp: '09200' },
  { colonia: 'Culhuacán', alcaldia: 'Iztapalapa', cp: '09800' },
  { colonia: 'Xochimilco Centro', alcaldia: 'Xochimilco', cp: '16000' },
  { colonia: 'La Noria', alcaldia: 'Xochimilco', cp: '16035' },
  { colonia: 'San Gregorio Atlapulco', alcaldia: 'Xochimilco', cp: '16600' },
  { colonia: 'Santa Cruz Xochitepec', alcaldia: 'Xochimilco', cp: '16800' },
  { colonia: 'San Juan Tepepan', alcaldia: 'Xochimilco', cp: '16020' },
  { colonia: 'Barrio San Antonio', alcaldia: 'Xochimilco', cp: '16090' },
  { colonia: 'Balbuena', alcaldia: 'Venustiano Carranza', cp: '15900' },
  { colonia: 'Aeronáutica Militar', alcaldia: 'Venustiano Carranza', cp: '15700' },
  { colonia: 'Morelos', alcaldia: 'Venustiano Carranza', cp: '15200' },
  { colonia: 'Merced Balbuena', alcaldia: 'Venustiano Carranza', cp: '15810' },
  { colonia: 'Felipe Ángeles', alcaldia: 'Venustiano Carranza', cp: '15220' },
  { colonia: 'Centro Urbano Presidente Alemán', alcaldia: 'Venustiano Carranza', cp: '15970' },
];

